spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8899/demo
    username: root
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10

